import { ConfigModule } from '@app/config/ConfigModule';
import ELASTICSEARCH_PROVIDERS from '@app/elasticsearch/providers';
import { ElasticsearchModuleImporter } from '@app/utils/elasticsearch/ElasticsearchModuleImporter';
import { ApolloDriver } from '@nestjs/apollo';
import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';

import { default as APP_SERVICES } from './appservices';
import { default as RESOLVERS } from './resolvers';
import { default as SERVICES } from './services';

@Module({
  imports: [
    ConfigModule.forRoot(),
    GraphQLModule.forRoot({
      driver: ApolloDriver,
      autoSchemaFile: 'autogenerated/schema.graphql',
    }),
    ElasticsearchModuleImporter,
  ],
  controllers: [],
  providers: [
    ...SERVICES,
    ...RESOLVERS,
    ...APP_SERVICES,
    ...ELASTICSEARCH_PROVIDERS,
  ],
})
export class AppModule {}
